WIP : 1115/i18n : Upgrade ngx-moment + Fix Function expressions are not sup…
theopenconversationkit/tock pull request #1197
Opened 2021-02-22 11:06 UTC by cedricjimenezst

…ported in decorators

2021-02-27 11:36 UTC, francoisno requested changes
Hi @cedricjimenezst thanks a lot for the PR, I will test it in the next days!
(And I'll be glad to work on #1115 with you if you're interested.)

Concerning this PR, it is no big deal but could you refactor it slightly (branch name, commit message, signed commit) to fit project conventions please? (https://github.com/theopenconversationkit/tock/blob/master/CONTRIBUTING.md)
Please let me know if you have questions.

2021-03-10 22:09 UTC, vsct-jburet commented
@francoisno can I merge this MR ?

2021-03-20 11:32 UTC, francoisno requested changes
Once the `ng2-charts` import is removed from NLP Admin, every works well.
I will rebase, amend the commit and merge manually the PR.
Thx again.

2021-03-20 11:32 UTC, francoisno commented on nlp/admin/web/src/app/quality-nlp/quality.module.ts
> +import {ChartsModule} from "ng2-charts";
This import/module breaks the build (at least after rebasing from master).

2021-03-20 11:59 UTC, francoisno commented
Merged manually.

2021-03-20 11:59 UTC, closed without merging