[Gen-Ai-Orchestrator] Add title to embedded documents for better retrieval
theopenconversationkit/tock pull request #1639
Opened 2024-06-18 09:10 UTC by GuirriecP

Adds the 'Title' entry of input CSV to embedded documents:
- during retrieval, the list of retrieved documents is more deterministic
- (seems to) slightly improves the quality of the generated answer
- fix the 'Text: ' préfix present in first chunks of source documents.

2024-06-18 09:47 UTC, vsct-jburet commented
@GuirriecP is it still draft ?

2024-06-18 13:47 UTC, GuirriecP commented
@vsct-jburet Yes it is. We will draft PRs to tell the Arkéa team members that the work is done, pending review. We will only push final, mergeable PRs to the repo when they have been reviewed.

2024-07-08 14:09 UTC, Benvii requested changes

2024-09-02 07:10 UTC, Benvii commented
@assouktim were did you fix this PR ? is there a new branch somewhere ? thanks in advance

2024-09-02 07:54 UTC, assouktim commented
Replaced by https://github.com/theopenconversationkit/tock/pull/1732

2024-09-02 07:54 UTC, closed without merging