[Tock studio] Vector DB settings
theopenconversationkit/tock pull request #1694
Opened 2024-07-22 13:37 UTC by rkuffer

Works with https://github.com/theopenconversationkit/tock/pull/1675

2024-08-28 14:12 UTC, assouktim requested changes

2024-08-28 14:12 UTC, assouktim commented on bot/admin/web/src/app/configuration/vector-db-settings/vector-db-provider-config-param-input/vector-db-provider-config-param-input.component.html
> +      <ng-container *ngIf="configurationParam.type === 'prompt'">
il ne peux pas y avoir de prompt pour cette configuration, je pense que tu peux supprimer ce bloc, et tout ce qui y est lié dans le composant

2024-08-28 14:21 UTC, rkuffer commented on bot/admin/web/src/app/configuration/vector-db-settings/vector-db-provider-config-param-input/vector-db-provider-config-param-input.component.html
> +      <ng-container *ngIf="configurationParam.type === 'prompt'">
Non c'est générique et à terme je songe à mutualiser avec d'autres composants utilisant le même mécanisme. J'aime autant le laisser

2024-09-03 15:15 UTC, Benvii approved these changes
Ok after the merge of https://github.com/theopenconversationkit/tock/pull/1675

2024-09-05 09:53 UTC, merged