Managing the deletion of AI configurations
theopenconversationkit/tock pull request #1725
Opened 2024-08-28 08:34 UTC by assouktim

2024-08-28 09:55 UTC, morgandiverrez requested changes

2024-08-28 09:55 UTC, morgandiverrez commented on bot/admin/server/src/main/kotlin/BotAdminService.kt
> +        // delete the RAG configuration
```suggestion
        // delete the Observability configuration
```

2024-08-28 09:55 UTC, morgandiverrez commented on bot/admin/server/src/main/kotlin/service/SentenceGenerationService.kt
> +     * Deleting the Observability Configuration
```suggestion
     * Deleting the LLM Sentence Generation Configuration
```

2024-08-28 09:55 UTC, morgandiverrez commented on bot/admin/server/src/main/kotlin/service/SentenceGenerationService.kt
> +            ?: WebVerticle.badRequest("No Observability configuration is defined yet [namespace: $namespace, botId: $botId]")
```suggestion
            ?: WebVerticle.badRequest("No LLM Sentence Generation configuration is defined yet [namespace: $namespace, botId: $botId]")
```

2024-08-28 09:55 UTC, morgandiverrez commented on bot/admin/server/src/main/kotlin/service/SentenceGenerationService.kt
> +        logger.info { "Deleting the Observability Configuration [namespace: $namespace, botId: $botId]" }
```suggestion
        logger.info { "Deleting the LLM Sentence Generation Configuration [namespace: $namespace, botId: $botId]" }
```

2024-08-28 15:19 UTC, morgandiverrez approved these changes

2024-09-03 14:56 UTC, Benvii approved these changes
Ok for me do we need to already create a ticket for vector db settings deletion ? 

2 options : 
- merging this PR first, rebasing https://github.com/theopenconversationkit/tock/pull/1675 and adding the deletion of vector DB settings.
- merging vector DB settings first then rebasing this PR and adding the deletion settings

2024-09-04 07:52 UTC, merged