[Docs] Gen AI
theopenconversationkit/tock pull request #1729
Opened 2024-08-29 13:35 UTC by assouktim

2024-09-10 08:14 UTC, assouktim commented
@Benvii : Reviewed and validated internally by Agnes.

2024-09-10 08:16 UTC, morgandiverrez approved these changes

2024-09-23 14:25 UTC, Benvii requested changes
Didn't manage to read all of it but here are my first comments

2024-09-23 14:46 UTC, assouktim commented on docs/_fr/user/studio/gen-ai/features/gen-ai-feature-rag-exclusion.md
> +![RAG Exclusions](../../../../img/gen-ai/gen-ai-rag-excluded-2.png "Ecran des sujets exlus de l'IA")
comme vu ensemble, à rajouter après pour chaque feature.

2024-10-09 10:33 UTC, assouktim commented on docs/_fr/user/studio/gen-ai/features/gen-ai-feature-rag-exclusion.md
> +![RAG Exclusions](../../../../img/gen-ai/gen-ai-rag-excluded-2.png "Ecran des sujets exlus de l'IA")
Finalement, je l'ai ajouté ;)

2024-10-09 13:15 UTC, Benvii commented
Todo : 

- [ ] `.md` links doesn't work
- [ ] table formatting to be done also

2024-10-09 15:15 UTC, Benvii approved these changes

2024-10-09 15:15 UTC, merged