[DERCBOT-1037] Use of PromptTemplate
theopenconversationkit/tock pull request #1772
Opened 2024-10-21 09:57 UTC by assouktim

2025-01-17 16:29 UTC, Benvii requested changes
Maybe it's because I'm not familiar with LCEL, it took me some time to understand the different part of the chain. I suggest add some comment (see my review comments) and / or rename some parts to make it a bit more explicit.

Otherwise good PR thanks I took the time to look at the langchain documentation also as it introduce new objects.

2025-01-17 16:29 UTC, Benvii commented on gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/rag_chain.py
> +def build_chat_chain(llm) -> ChatPromptTemplate:
Can you use a more explicit naming like build_question_condensation_chain ?

2025-01-17 16:29 UTC, Benvii commented on gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/rag_chain.py
> +    rag_chain_with_source = contextualize_question_fn | RunnableParallel(
A suggestion to be more explicit : 
```suggestion
    rag_chain_with_retriever = contextualize_question_fn | RunnableParallel(
```

2025-01-17 16:29 UTC, Benvii commented on gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/rag_chain.py
> +    rag_chain = construct_rag_chain(llm, rag_prompt)
It's not the full chain it's only the task of asking the LLM a rag task, augmented generation .. it's a bit confusing .. maybe add a comment indicating that this chain expect that the documents are already retrieved ?

2025-01-21 09:15 UTC, assouktim commented on gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/rag_chain.py
> +                and response['documents'] == []
yes, the conflict must be corrected in the last PR merged between the two

2025-01-22 16:30 UTC, Benvii commented on gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/rag_chain.py
> +                and response['documents'] == []
Thanks it can be rebased now 👍️

2025-01-30 12:46 UTC, Benvii approved these changes
thanks for the updates 😀

2025-01-30 14:08 UTC, rkuffer approved these changes

2025-01-30 14:09 UTC, merged