[DERCBOT-1250] FAQ by namespace
theopenconversationkit/tock pull request #1783
Opened 2024-11-05 11:37 UTC by assouktim

2024-11-18 13:59 UTC, Benvii approved these changes
LGTM, thanks 👍️

2024-11-18 14:00 UTC, Benvii requested changes
LGTM, thanks 👍️

- [ ]  Just remove changes on pom.xml files

2024-11-19 09:46 UTC, assouktim commented
It's done

2024-11-19 14:47 UTC, AurelienSylvan approved these changes

2024-11-19 14:53 UTC, merged