[DERCBOT-1267] Gen AI - Document Compressor
theopenconversationkit/tock pull request #1788
Opened 2024-11-18 15:16 UTC by assouktim

This pull request adds support for a new Document Compressor feature in the bot administration service. The changes include adding new data models, services, and API endpoints to manage the Document Compressor configuration. Additionally, some existing code has been updated to integrate this new functionality.

### Document Compressor Feature:
* [`bot/admin/server/src/main/kotlin/BotAdminService.kt`](diffhunk://#diff-247695b29ea9fe29753c2a141fd2c331950837b442b867c2b0927360e27fdedeR32): Added `BotDocumentCompressorConfigurationDAO` and implemented methods to delete the Document Compressor configuration. [[1]](diffhunk://#diff-247695b29ea9fe29753c2a141fd2c331950837b442b867c2b0927360e27fdedeR32) [[2]](diffhunk://#diff-247695b29ea9fe29753c2a141fd2c331950837b442b867c2b0927360e27fdedeR87) [[3]](diffhunk://#diff-247695b29ea9fe29753c2a141fd2c331950837b442b867c2b0927360e27fdedeR1172-R1176)
* [`bot/admin/server/src/main/kotlin/BotAdminVerticle.kt`](diffhunk://#diff-7b5a0b9d2cc2c7c29eb635b0ed7bb471c5864c6e2512424b0df61abae72a5f5fR483-R501): Added new API endpoints to handle CRUD operations for the Document Compressor configuration.
* [`bot/admin/server/src/main/kotlin/model/BotDocumentCompressorConfigurationDTO.kt`](diffhunk://#diff-d4b9cac4a52f9ea0168940bdbbe9f6474c93c7a26fd7feff4c60189c4ab02ed4R1-R51): Created a new data transfer object for the Document Compressor configuration.
* [`bot/admin/server/src/main/kotlin/service/DocumentCompressorService.kt`](diffhunk://#diff-378b03954ecd3bb2a6dd81a01499331c2685726c636b1897d38ca541022ca59fR1-R110): Implemented the service to manage Document Compressor configurations, including validation and error handling.
* [`bot/admin/server/src/main/kotlin/service/DocumentCompressorValidationService.kt`](diffhunk://#diff-e35dae771a6e79b12116a6a9d22a15313f519ea8405e6ec874d5615c558831e0R1-R49): Added a validation service to check the Document Compressor configuration settings.

### Other Changes:
* `bot/connector-rest-client/src/main/kotlin/model/ClientFootnote.kt` and `bot/connector-web-model/src/main/kotlin/ai/tock/bot/connector/web/send/Footnote.kt`: Added a new `score` field to the `Footnote` data class. [[1]](diffhunk://#diff-f4b2df36210044358b16e95e2439745ac82df4cff6ce2eacd37bcf6443b4950aL26-R27) [[2]](diffhunk://#diff-535563ec28e6b0bfb82a3cb6cc05dcdecea305e3e53a7c68a2eeb04ea723699dR40-R43)
* `bot/connector-web/src/main/kotlin/WebMessageProcessor.kt` and `bot/connector-web/src/test/kotlin/WebConnectorResponseTest.kt`: Updated the `WebMessageProcessor` and its test to handle the new `score` field in `Footnote`. [[1]](diffhunk://#diff-c333f2deab24ed95ceb6a66a9a84f286c4821695dc18825bdc33854a96301e1eL46-R47) [[2]](diffhunk://#diff-5bcd4b033dc30f1b1d33443ab21b160ebf8e8ff98cd3b4de61e9fe341abb8a82L54-R55)
* `bot/engine/src/main/kotlin/admin/bot/compressor/BotDocumentCompressorConfiguration.kt` and `bot/engine/src/main/kotlin/admin/bot/compressor/BotDocumentCompressorConfigurationDAO.kt`: Added new data models and DAO interfaces for the Document Compressor configuration. [[1]](diffhunk://#diff-07c76352dcb149ee80f719bb4075f24da79fb634a1946e735a8048461202094dR1-R28) [[2]](diffhunk://#diff-e5d7c19e133f774e034720834cf6524090f03033ebcad4fee4d77c604615ad47R1-R32)
* `bot/engine/src/main/kotlin/definition/BotDefinition.kt` and `bot/engine/src/main/kotlin/definition/BotDefinitionBase.kt`: Updated the `BotDefinition` and `BotDefinitionBase` to include the Document Compressor configuration. [[1]](diffhunk://#diff-09ba4d186f9b164b77ae41fe79c8c80f0398ce831cd12bf64d6dc0e45152759dR19) [[2]](diffhunk://#diff-09ba4d186f9b164b77ae41fe79c8c80f0398ce831cd12bf64d6dc0e45152759dR138-R142) [[3]](diffhunk://#diff-6949264ee2afc95f02c9a42fba9a28f0cba5e9e476918326cbacc964a3cefdd2R19) [[4]](diffhunk://#diff-6949264ee2afc95f02c9a42fba9a28f0cba5e9e476918326cbacc964a3cefdd2L65-R67)
* [`bot/engine/src/main/kotlin/engine/BotRepository.kt`](diffhunk://#diff-140908ffb248823237fbe14febabd2a60a4c4d8cb6fe517f07eaf7fc13907502R45): Added import for `BotDocumentCompressorConfigurationMonitor`.

2025-01-10 13:09 UTC, Benvii requested changes
Thanks for adding all the check document compressor settings to the orchestrator 👍️, juste a small comment about an exception raising that could be improved.

We begin to have a lot of Gen AI related configuration directly on the Bot Definition, I'm not sure but in a futur refactory I might be a good option to group them especially if we want to expose the to python scripted stories (tock-py) and also kotlin scripted stories. It would be great to have access to some BotDefinition configurations inside buildin sotries (stories behind the Bot API). Maybe we should create an issue about that.
My idea is in a near futur to expose Gen AI settings to build in stories (especially python, tock-py ones) so that python developpers could easily build there own langchain chains using the bot settings and the gen-ai-orchestrator factories provided in a separated python package.

We also have a lot of gen ai related configuration endpoint directly on the bot admin verticle we should in the futur group them in a different verticle.

2025-01-10 13:09 UTC, Benvii commented on bot/admin/server/src/main/kotlin/service/ObservabilityValidationService.kt
> +                    .checkSetting(ObservabilityProviderSettingStatusQuery(config.setting))
Good catch 👍️

2025-01-10 14:44 UTC, assouktim commented on gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/impls/document_compressor/bloomz_rerank.py
> +        except Exception as exc:
yes, absolutely

2025-01-10 14:47 UTC, assouktim commented on gen-ai/orchestrator-core/src/main/kotlin/ai/tock/genai/orchestratorcore/models/Constants.kt
> +    const val GEN_AI_COMPRESSION="$GEN_AI/COMPRESSION"
yes, I'm going to delete it, it's not in use now.

2025-01-10 15:37 UTC, assouktim commented
> Thanks for adding all the check document compressor settings to the orchestrator 👍️, juste a small comment about an exception raising that could be improved.
> 
> We begin to have a lot of Gen AI related configuration directly on the Bot Definition, I'm not sure but in a futur refactory I might be a good option to group them especially if we want to expose the to python scripted stories (tock-py) and also kotlin scripted stories. It would be great to have access to some BotDefinition configurations inside buildin sotries (stories behind the Bot API). Maybe we should create an issue about that. My idea is in a near futur to expose Gen AI settings to build in stories (especially python, tock-py ones) so that python developpers could easily build there own langchain chains using the bot settings and the gen-ai-orchestrator factories provided in a separated python package.
> 
> We also have a lot of gen ai related configuration endpoint directly on the bot admin verticle we should in the futur group them in a different verticle.

Yes, we need to include it in the analysis when we refactor the orchestrator code. We need to put this in a separate ticket.

2025-01-10 15:39 UTC, assouktim commented on gen-ai/orchestrator-core/src/main/kotlin/ai/tock/genai/orchestratorcore/models/compressor/BloomzDocumentCompressorSetting.kt
> +    val maxDocuments: Int,
it is already required for Tock Studio, botApi and botAdmin

2025-01-13 14:45 UTC, Benvii commented on gen-ai/orchestrator-core/src/main/kotlin/ai/tock/genai/orchestratorcore/models/compressor/BloomzDocumentCompressorSetting.kt
> +    val maxDocuments: Int,
Ok

2025-01-13 14:46 UTC, Benvii commented on gen-ai/orchestrator-core/src/main/kotlin/ai/tock/genai/orchestratorcore/models/Constants.kt
> +    const val GEN_AI_COMPRESSION="$GEN_AI/COMPRESSION"
Thanks

2025-01-13 14:55 UTC, Benvii approved these changes
Thanks for the updates, I've created a separated issue here : 

- #1822

2025-01-13 14:58 UTC, rkuffer approved these changes

2025-01-13 14:58 UTC, merged