[DERCBOT-1283] Generate dataset - New Excel template
theopenconversationkit/tock pull request #1803
Opened 2024-12-06 15:51 UTC by assouktim

2025-01-17 16:03 UTC, assouktim commented
@Benvii It is now ready for review

2025-01-20 10:28 UTC, Benvii requested changes
Thanks for the updates, see my few comments : small changes / suggestions.

2025-01-20 10:28 UTC, Benvii commented on gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/generate_dataset.py
> +    # Data extraction
```suggestion
    # Data extraction
    # Using panda lines and columns are numbered from 0, row 8 match with raw "I" in excel or LibreOffice
```

2025-01-20 10:28 UTC, Benvii commented on gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/generate_dataset.py
> +    topics = df.iloc[2, 8:].tolist()     # Line 1: Topic
```suggestion
    topics = df.iloc[2, 8:].tolist()     # Line 2 (line 3 in excel or LibreOffice): Topic
```

2025-01-20 10:28 UTC, Benvii commented on gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/generate_dataset.py
> +    questions = df.iloc[3, 8:].tolist()  # Line 2: Question
```suggestion
    questions = df.iloc[3, 8:].tolist()  # Line 3 (line 4 in excel or LibreOffice): Question
```

2025-01-20 10:28 UTC, Benvii commented on gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/generate_dataset.py
> +    answers = df.iloc[4, 8:].tolist()    # Line 3: Expected answer
```suggestion
    answers = df.iloc[4, 8:].tolist()    # Line 4 (line 5 in excel or LibreOffice): Expected answer
```

2025-01-20 10:28 UTC, Benvii commented on gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/generate_dataset.py
>      load_dotenv()
I run it locally an noticed that the .env file is committed, this will lead developpers to commit their configurations can you rename it .example.env for instance and add .env to a local .gitignore file

2025-01-20 10:28 UTC, Benvii commented on gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/export_run_results.py
> +    wb = load_workbook("examples/generate_dataset_input.example.xlsx")
If the script isn't executed from it's location folder this path won't work.

```suggestion
    script_dir = os.path.dirname(os.path.abspath(__file__))
    
    wb = load_workbook(os.path.join(script_dir, "examples/generate_dataset_input.example.xlsx"))
```

2025-01-20 13:17 UTC, assouktim commented on gen-ai/orchestrator-server/src/main/python/tock-llm-indexing-tools/generate_dataset.py
>      load_dotenv()
The example file for ‘.env’ is with the other examples in ./examples

2025-01-30 14:08 UTC, rkuffer approved these changes

2025-01-30 14:09 UTC, merged