[DERCBOT-1314] Add documentsRequired Setting to BotRAGConfiguration for RAG Logic Enhancement
theopenconversationkit/tock pull request #1814
Opened 2024-12-23 10:10 UTC by scezen

### Related Tickets
JIRA: **[DERCBOT-1314]**

### Description

This PR introduces a new boolean attribute `documentsRequired` to the `BotRAGConfiguration` and integrates it across the system. The `documentsRequired` attribute determines whether documents are mandatory for processing the RAG chain.

### Key Changes:
1. **Model Updates**:
    - Added `documentsRequired` to [`BotRAGConfiguration`](bot/engine/src/main/kotlin/admin/bot/rag/BotRAGConfiguration.kt) (default: `true`) and [`BotRAGConfigurationDTO`](bot/admin/server/src/main/kotlin/model/BotRAGConfigurationDTO.kt)
    - Ensured backward compatibility by handling cases where `documentsRequired` is absent in the database.

2. **Orchestrator Enhancements**:
    - Updated [`RAGQuery`](gen-ai/orchestrator-client/src/main/kotlin/ai/tock/genai/orchestratorclient/requests/RAGQuery.kt) to include `documentsRequired` as an optional parameter.
    - Modified `__rag_guard` in [`rag_chain.py`](gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/rag_chain.py) to respect the `documentsRequired` setting.

3. **Bot API Modifications**:
    - Updated [`RAGAnswerHandler`](bot/engine/src/main/kotlin/engine/config/RAGAnswerHandler.kt) to fetch the `documentsRequired` setting from the bot configuration and pass it to the RAG query.

### Testing :
- We can block the retrieval of documents by adding a filter to [`pgvectors_params.py`](gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/models/vector_stores/pgvector/pgvector_params.py) as so: 

```
    def to_dict(self):
        return {
            'k': self.k,
            'filter': {'tag1': 'vector stores'},
        }
```
- Then we are free to test if an answer is still provided while no retrieval of document is made.

2025-01-08 13:37 UTC, assouktim requested changes
LGTM, just update the unit tests (python) and everything should be ready.

2025-01-10 14:42 UTC, scezen commented
Tests added @assouktim

2025-01-13 09:04 UTC, assouktim approved these changes
Thanks a lot.

2025-01-16 10:53 UTC, scezen commented
Fixed the edge case, now handles missing documents without 'no_answer' configuration @Benvii

2025-01-16 13:37 UTC, Benvii requested changes
- [ ] Remove the last condition see my comment.
- [ ] Add a test without the 'no_answer' input to check that it works

2025-01-16 13:37 UTC, Benvii commented on gen-ai/orchestrator-server/src/main/python/server/src/gen_ai_orchestrator/services/langchain/rag_chain.py
> +        # Unexpected behavior: chain replied with 'no_answer' but documents are present
It's not unexpected sometimes documents found by the retriever doesn't contain the answer to the question. It can happen especially when we don't have any compressor as it will alsways find documents.

2025-01-22 16:20 UTC, Benvii approved these changes
Thanks for the last updates ok for me.

2025-01-22 16:23 UTC, merged